#!/bin/bash

valid_username="user1"
valid_password="password1"
echo “please enter a username:”
read username
echo "please enter a password:”
read password
if [[ ${username} == ${valid_username} ]] && [[ ${password} == {valid_password ]];

then
	echo “Username and Password are valid !!!”
else
	echo “Username and or Password are invalid !!!”  
fi 
# EOF


